### ISSUE TITLE
TypeError: Can't mix strings and bytes in path components

### ISSUE THREAD

**Issue by santosh-shriyan** [Lornatang/SRGAN-PyTorch#27]
```
I am trying to do inference on one of the default dataset images suggested in the Readme.md


`user#:/home/ubuntu/SRGAN-PyTorch# python test_image.py --arch srgan --lr /home/ubuntu/SRGAN-PyTorch/data/train/0001.png --hr /home/ubuntu/SRGAN-PyTorch/data/0001_HR.png --model-path /home/ubuntu/SRGAN-PyTorch/weights/lpips_vgg.pth --pretrained --gpu 0
[ WARNING ] Directory `/home/ubuntu/SRGAN-PyTorch/tests` already exists!
[ INFO ] TestEngine:
[ INFO ] 	API version .......... 0.3.0
[ INFO ] 	Build ................ 2021.06.13
[ INFO ] Using pre-trained model `srgan`.
Traceback (most recent call last):
  File "test_image.py", line 150, in <module>
    main(args)
  File "test_image.py", line 59, in main
    model = configure(args)
  File "/home/ubuntu/SRGAN-PyTorch/srgan_pytorch/utils/common.py", line 46, in configure
    model = models.__dict__[args.arch](pretrained=True)
  File "/home/ubuntu/SRGAN-PyTorch/srgan_pytorch/models/generator.py", line 104, in srgan
    return _gan("srgan", pretrained, progress)
  File "/home/ubuntu/SRGAN-PyTorch/srgan_pytorch/models/generator.py", line 92, in _gan
    state_dict = load_state_dict_from_url(model_urls[arch], progress=progress, map_location=torch.device("cpu"))
  File "/opt/conda/lib/python3.8/site-packages/torch/hub.py", line 517, in load_state_dict_from_url
    cached_file = os.path.join(model_dir, filename)
  File "/opt/conda/lib/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/opt/conda/lib/python3.8/genericpath.py", line 155, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```
`

facing similar problem while test_benchmark as well.

**Comment by Lornatang** [comment]
Sorry, I haven't uploaded the new weight yet.

**Comment by santosh-shriyan** [comment]
okay, let me know when you make them available.
appreciate the quick reply.

**Comment by CatalinOAlexandru** [comment]
> Sorry, I haven't uploaded the new weight yet.

I trained my own model and I attempted to benchmark as well, but I have the same problem.
Will different weights fix this issue? As the problem looks to be the way some path is encoded somewhere.

**Comment by LIUHUACHENG** [comment]
> Sorry, I haven't uploaded the new weight yet.

hello,I also meet this problem,do you know how to fix it ？

**Comment by Lornatang** [comment]
7.5 soon

**Comment by pankhurivanjani** [comment]
Hello! I am also facing the same problem and looking forward to new weights.

**Comment by PhilipMachineLearning** [comment]
Same error for video:

Traceback (most recent call last):
  File "test_video.py", line 170, in <module>
    main(args)
  File "test_video.py", line 59, in main
    model = configure(args)
  File "/content/SRGAN-PyTorch/srgan_pytorch/utils/common.py", line 46, in configure
    model = models.__dict__[args.arch](pretrained=True)
  File "/content/SRGAN-PyTorch/srgan_pytorch/models/generator.py", line 104, in srgan
    return _gan("srgan", pretrained, progress)
  File "/content/SRGAN-PyTorch/srgan_pytorch/models/generator.py", line 92, in _gan
    state_dict = load_state_dict_from_url(model_urls[arch], progress=progress, map_location=torch.device("cpu"))
  File "/usr/local/lib/python3.7/dist-packages/torch/hub.py", line 546, in load_state_dict_from_url
    cached_file = os.path.join(model_dir, filename)
  File "/usr/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.7/genericpath.py", line 155, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components

**Comment by Lornatang** [comment]
New weights upload
