### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by angrebobo** [Lornatang/SRGAN-PyTorch#73]
Traceback (most recent call last):
  File "/tmp/huangsibo/srgan/train_srgan.py", line 26, in <module>
    from dataset import CUDAPrefetcher, TrainValidImageDataset, TestImageDataset
  File "/tmp/huangsibo/srgan/dataset.py", line 32, in <module>
    class TrainValidImageDataset(Dataset):
  File "/tmp/huangsibo/srgan/dataset.py", line 57, in TrainValidImageDataset
    def __getitem__(self, batch_index: int) -> [dict[str, Tensor], dict[str, Tensor]]:
TypeError: 'type' object is not subscriptable

**Comment by Satyajit1993** [comment]
How to solve this error

def getitem(self, batch_index: int) -> [dict[str, Tensor], dict[str, Tensor]]:
TypeError: 'type' object is not subscriptable

**Comment by Lornatang** [comment]
Wait me fix this error

**Comment by whatseob** [comment]
i got same error. how can i solve?
