### ISSUE TITLE
Traceback (most recent call last):   File "F:\SRGAN-PyTorch-main\test.py", line 190, in <module>     main()   File "F:\SRGAN-PyTorch-main\test.py", line 169, in main     config["ONLY_TEST_Y_CHANNEL"], KeyError: 'ONLY_TEST_Y_CHANNEL'

### ISSUE THREAD

**Issue by colorfulorange666** [Lornatang/SRGAN-PyTorch#81]
When I run test.py and have already modified the yaml file, it always has report this error to me,how can I correct it?Thanks for your response.

**Comment by Lornatang** [comment]
Fixed. Thank you.
