### ISSUE TITLE
Issues running the test.py

### ISSUE THREAD

**Issue by acamargofb** [Lornatang/SRGAN-PyTorch#88]
test.py --config_path ./configs/test/SRGAN_x4-SRGAN_ImageNet-Set5.yaml
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    from dataset import CUDAPrefetcher, PairedImageDataset
  File "/mnt/c/Users/User/Desktop/Personal/UNI/SRGAN/SRGAN-PyTorch-main/SRGAN-PyTorch-main/dataset.py", line 25, in <module>
    from imgproc import image_to_tensor, image_resize
  File "/mnt/c/Users/User/Desktop/Personal/UNI/SRGAN/SRGAN-PyTorch-main/SRGAN-PyTorch-main/imgproc.py", line 514, in <module>
    center: tuple[(int, int)] = None,
TypeError: 'type' object is not subscriptable

**Comment by Lornatang** [comment]
I use Python=3.10.x

**Comment by acamargofb** [comment]
Thanks, it is working now

**Comment by acamargofb** [comment]
One question, what is the maximum size of image that this model can handle as input? I mean 256x256x3? what value?. or this depends on the GPU memory?

**Comment by Lornatang** [comment]
Yeah. For GPU memory~
